### ISSUE TITLE
Front with Design Gouv Accueil

### ISSUE THREAD

**Issue by GalloIT** [betagouv/anssi-nis2#1]
```[tasklist]
### Tasks
- [x] Header
- [x] Footer
- [x] Bandeau principal
- [x] Suis-je concerné ?
- [x] NIS2, la nouvelle directive européenne cyber
- [x] Les entités concernées devront se conformer à certaines obligations auprès de l’ANSSI
- [x] quand se préparer ?
- [x] Qui est l’ANSSI ?
- [x] Lettre d'infirmation et réseaux sociaux
```
