### ISSUE TITLE
Creation des premières étapes CI

### ISSUE THREAD

**Issue by GalloIT** [betagouv/anssi-nis2#11]
```[tasklist]
### Tasks
- [x] Build sur Github actions
- [x] Réorg TU
- [ ] TU sur GHA
- [ ] Ajout de Prettier + GHA
- [ ] [Optionnel]Ajout d'un Test UI sur page d'accueil
- [ ] [Optionnel]Ajout d'un Test UI du simulateur
```
